rolling-scopes-school/tasks

tasks/game.md
=> Add useful link to game.md

tasks/youtube.md
More correct formulation for supporting mobile browser
=> youtube.md requirement change

tasks/codewars.md
codewars.md to english translated
=> codewars.md translation

tasks/create_form.md
create_form.md to english translated
=> create_form translation

tasks/critical-rendering-path.md
critical-rendering-path.md to english translated
=> critical-rendering-path.md translation

tasks/columns.md
columns.md to english translated
=> columns.md translation

tasks/english.md
Is it necessary to translate student's recomendations?
=> feat: english-task to eng translate

tasks/codejam-scoreboard.md
Адна невялічкая папраўка:
- паменены месцамі пункты адзнакі, каб спачатку былі ўсе плюсы, а прыканцы быў мінус:
-50 баллов за нарушение
+30 баллов Добавить возможность простмотреть участников
=> Scoreboard translate

tasks/interview-corejs.md
Eng translation to interview-corejs add
=> feat: interview-corejs eng translation add

tasks/interview-corejs.md
Reverts rolling-scopes-school/tasks#62
=> Revert "feat: interview-corejs eng translation add"

tasks/float_exercise.md
Please look thru the translation and merge upon approval
=> This adds translation for float_exercise.md

tasks/accessibility.md
Please 👀 if everything is fine
=> This adds translation for accessibility.md

tasks/codejam-corejs.md
Please check the translation of the task
=> codejam-core.js translation into English

tasks/float_layouts.md
The task float_layouts.md has been fully translated in English. Please review and merge the changes. Thanks)
=> This adds translation for float_layouts.md

tasks/codewars.md
More comfortable navigate in codewars links
=> docs: formated list in codewars task

tasks/markup-d2-NeutronMail-en.md
Задание NeutronMail содержит требование создать СВОЙ приватный репозиторий. С другой же стороны, требования к сдаче заданий второго этапа предусматривают необходимость заливать задания в приватный репозиторий, ВЫДАННЫЙ Школой Rolling Scopes. Внес необходимые исправления.
=> fix: indicate proper repositoty

tasks/codejam-pallete.md
=> style: change link on requirements for commits, PR, repository

tasks/codejam-notification.md
@PavalEscoba, please check the translation before merging.
The picture previously hosted on [http://varabei.com/](http://varabei.com/public/codejam-2-dom.png) now is loaded to my repo
=> Add codejam-notification task translation

tasks/piskel-clone.md
In current file version we can't meet branch name requirements, so i propose to add it in requirements
=> add branch name column

tasks/HTML_CSS_self.md
There are many questions about which exactly course they need to complete: whether Codecademy or HTMLAcademy? If it is a really important requirement - I suggest to make requirements about "Must" and "Desirable" much noticeable.
=> docs: make demands noticeable

tasks/markups/level-3/repair-design-project/repair-design-project-draft.md, tasks/markups/level-3/repair-design-project/repair-design-project-en.md
Fix some typo in section **Terms of Reference**
=> Fix some typo

tasks/codewars.md
In order to help other people I added kyu (difficulty level) before each codewars task link in the list.
=> kyu for codewars task list

tasks/codewars.md
There are 11 tasks of 6 kyu in the list, but NOT 14!
=> fix small typo in task description

tasks/stage-2/codejam-canvas/codejam-canvas.md
Fix some typos and modify markup
=> Fix typos in codejam-canvas task

tasks/codejam-cv.md, tasks/rss-mentor-dashboard.md
Translate codejam CV task and mentor dashboard into English.
This PR is part of #45
=> Translate codejam cv & mentor dashboard into English

tasks/fancy-weather.md
Добавил flickr api в таск fanсy-weather. На flickr на порядки больше фото, чем на unsplash, правда и api на много больше и сложнее.
=> add flickr api in fancy weather

tasks/codewars-stage-1.md
Add tasks from Codewars for stage 1
=> codewars stage 1

tasks/codejam-culture-portal.md
Maximum points is **240**, instead **280**
Extra scope score is **70** instead of **90**
Or maybe there's another logic of sum of points that I didn't realize 🤷🏻‍♂️
=> fix: fix score calculation

tasks/css-recipes.md, tasks/markup-1.md
Translate css-recipes and markup-1 into English
=> Translate tasks poland

tasks/git-markdown.md
I've added translation to FAQ section of Markdown & Git task
=> docs: translate into english markdown & git faq section

tasks/codewars.md
Add auto-check tool for students' self-checking while solving problems and change style to bold header of the task & total points paragraph
* Auto-check from here:
https://github.com/rolling-scopes-school/tasks/blob/master/tasks/codewars-stage-1.md
=> Add auto-check like in the codewars-stage1-tasks

tasks/fancy-weather.md
- Обновлены примеры weather API
- Удален Dark Sky weather API, т.к. он более не предоставляет ключи
=> fix: update weather APIs (2020q1)

tasks/presentation.md
- Requirements are so exact "phone's camera" (but, it don't necessarily must be the phone's camera: e.g. webcam, videocam);
- Requirements are different in the **Passing the task** & **Evaluation criteria** sections. According to the **Evaluation criteria** section, slides **MUST** be in the video, but they **SHOULD NOT** necessarily be recorded on the camera;
- Change header stylings (make Presentation header h2 & Requirements header h3);
=> docs: update headers & make requirements more accurate

tasks/rslang/english-for-kids-translated.md
English for kids task translation from Russian to English
=> english-for-kids-2020-translation: add English translation

tasks/codejam-the-gem-puzzle(en).md
Translated **codejam-the-gem-puzzle** into English.
=> Add codejam-the-gem-puzzle(en)

tasks/rslang/rslang.md
add aggregated word endpoint description
=> doc: add aggregated word endpoint description

tasks/rslang/rslang.md
add a description to aggregated endpoints
=> doc: add description to aggregated endpoints

tasks/rslang/rslang.md
change description according to backend changes
=> doc: change description according to backend changes

tasks/rslang/rslang.md
add word assets retrieving description
=> doc: add word assets retrieving description

tasks/songbird/birds.js
Исправлены битые ссылки на изображения
=> fix image links in songbird task

tasks/angular/intro.md
Propose functionality oriented project structure as a default one
=> chore: propose functionality oriented project structure

tasks/presentation.md
Changed Advanced scope requirements:
- Changed 20 points `for courage` with 10 points.
- Specified that camera is obligatory on online performing
- Added notice about agreement with recording during online performing.
=> Improve Presentation task requirements

tasks/interview-corejs.md
Убрал вопросы касающиеся prototype и всего, что с ним связано. На данный момент в интервью они практически не встречаются. Добавил раздел с практическими задачами.
=> Подредактировал задачи и вопросы для интервью

stage0/modules/css-basics/README.md
there were questions in the Discord chat, perhaps the name should be clarified as in the RS app
=> docs: change name test "CSS Test #0" to "Test CSS Basics [RU]"

stage0/modules/git/README.md
maybe need add this text in README.md by analogy with the "Test HTML Basics [RU]" 
https://github.com/rolling-scopes-school/tasks/tree/master/stage0/modules/html-basics
=> docs: add "Git Test [RU]" in stage0 week#2

tasks/js30/js30-5.md
=> docs: youtube link

stage0/modules/js-basics/README.md
=> Add test name

tasks/js30/js30-2.md
Fixed link to proper demo page
=> fix: fix link to demo

stage1/README.md
Сокращено время выполнения проектов Museum. DOM и Momentum  с двух недель до одной, добавлен проект ArtQuiz и свободная от тасков неделя для подготовки к собеседованию
<details>
<summary>Подробный список правок</summary>
1. в первую неделю, в которой изучается Git, добавлены 1-2 части таска CV 
2. во вторую неделю добавлен модуль "Codewars1"
3. в третью неделю, в которой начинается выполнение проекта "Virtual Museum", перенесён из 9 недели модуль Sass, использование которого рекомендуется в данном таске
4. Объединены 4-5 недели, за счёт сокращения времени выполнения задания "Virtual Museum. DOM & Browser API" с двух недель до одной. Требования этой части задания тоже немного сокращены
5. в шестую неделю добавлен модуль "Codewars2"
6. объединены 8-9 недели, за счёт сокращения времени …
=> update stage#1 readme

tasks/materials/english.md
=> feat: add another interactive course

stage0/modules/basic-tools/README.md, stage0/modules/js-fe-developer/README.md, stage1/modules/chrome-devtools/README.md, stage1/modules/functions/README.md, stage1/modules/js-basics/README.md
Change descriptions for the first week and stage0: basic tools, roadmap modules
=> Add tests naming

stage0/modules/css-positioning/README.md, stage0/modules/figma/README.md, stage1/modules/css-grid/README.md
Add test names for Figma, CSS Grid and Positioning, Flex modules
=> Add test names

stage2/modules/typescript-advanced/README.md, stage2/modules/typescript-basic/README.md
Добавил ссылку на интерактивный курс по TypeScript от Microsoft в файл README.md директории typescript-basic
=> feat: add link on course TypeScript

stage0/README.md, stage0/modules/data-structures-part-1/README.md, stage0/modules/data-types/README.md, stage0/modules/figma/README.md, stage0/modules/git/README.md, stage0/modules/js-basics/README.md, stage0/modules/js-functions/README.md, stage0/modules/objects-and-arrays/README.md
Draft until all tasks will be added
=> [Draft] Stage 0 Modules

tasks/cv/cv-hints.md
=> fix git-markdown

tasks/cv/cv-hints.md
=> fix hints cv

tasks/portfolio/portfolio-part2-hints.md
Changes in background-position, background-size. % to fix size.
=> fix: update Adaptive background image

tasks/cv/cv-hints.md
=> Text correction

stage1/modules/css-grid/README.md
Вставлены правильные markdown ссылки в секцию "Теория".
=> docs: update CSS grid README.md

stage1/modules/clean-code/materials/generic-principles.md
- replace [`getDay`]( https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/getDay) with `toLocaleDateString`
-  fix `weekday` capitalization 
- modify console.log statement actually to print string representation of `today`
=> Fix functions examples in DRY code section

stage2/modules/classes-prototypes/README.md
Consider merging this small fix.
=> fix: update link naming

stage1/modules/node-materials/node/stream-readable.md
"При наступлении события `'end'` выведем в консоль сообщение и длину полученных данных:"  в конце выводило дату, а не её длинну
=> fix: typo (data -> data.length)

tasks/materials/algorithms.md
A sorted array is mandatory for Binary Search.
Binary Search should return searched item index.
Implemented two variants of binary search (iterative and recursive).
=> Fix: Materials - Algorithms - Binary Search

stage2/modules/oop-basics/README.md, stage2/modules/typescript-advanced/README.md, stage2/modules/typescript-basic/README.md
add oop, ts: basic, ts: advanced
=> add tests to modules

tasks/codewars/preschool-2022-codewars1.md
Во второй и третьей части codewars для preschool-2022 сложность заданий указана, в первой части - нет.
https://github.com/rolling-scopes-school/tasks/blob/master/tasks/codewars/preschool-2022-codewars1.md
https://github.com/rolling-scopes-school/tasks/blob/master/tasks/codewars/preschool-2022-codewars2.md
https://github.com/rolling-scopes-school/tasks/blob/master/tasks/codewars/preschool-2022-codewars3.md
Предлагаю добавить сложность и в первую часть.
=> fix: add difficulty to preschool-2022-codewars1.md

stage0/README.md, stage0/modules/git/README.md
Added point 8 in the section "Additional materials"
=> Updated README.md

stage2/modules/async/README.md
1) Fix formatting
2) Delete unavailable link
=> Fix: Stage#2 - Module "Async programming" - fix formatting

stage1/modules/node-materials/README.md
There is an online casino now :( https://nodeguide.ru/doc/
=> docs: delete broken link

react_week_1.md
1. translation for this module: 
https://github.com/rolling-scopes-school/tasks/tree/master/react/modules/module01
2. screenshot:
3. discussion:
https://github.com/rolling-scopes-school/tasks/issues/736
4. done 20.07.2022
*in Score section mentioned march month, not sure which one should be there, so left it as is
=> feat: translate week 1 react course

stage1/README.md
add links to tests on the basics of HTML and CSS
=> docs: add links

stage1/modules/client-server/README.md
https://github.com/rolling-scopes-school/tasks/issues/623
=> feat: add client - server test

react/modules/module02/README.md
To my opinion, the meaning of the following requirement is not clear:
> After changing value in input, then reset will happens only for one particular field (not all fields). 
During the completion of the task I had to look back in the Russian version of it to clarify this. So I suggest to paraphrase it:
> After changing the value of erroneous input, the reset should happen only for this particular field, but not for the others.
Also, I suggest to reformat the task description the following way:
- make a list of input types
- specify the input type text for the first form control (just _input_ has very broad meaning)
- move blocks with the description of creation of cards before validation, because in validation block there is a mention of cards
- fix grammar & typos
=> Fix translation issues & grammar

react/modules/module03/README.md
"Enter test" change to "Enter text"
=> Fix syntax error

stage1/modules/webpack/README.md
Немного актуализировал ссылки.
Старую ссылку перенес в доп.материалы и добавил туда ссылку на оф.сайт webpack. Добавил ссылки на два, вроде бы, самых свежих вебинара по webpack.
=> stage1 webpack module update

stage1/modules/node-materials/README.md
fix link to youtube playlist instead of blog article
=> docs: fix link

tasks/songbird/birds-en.js, tasks/songbird/songbird-2022q3.md
- add new file `birds-en.js` with `birdsDataEn` class - translation of `birds.js` file
- add link for this file to docs: `songbird-2022q3.md`
=> Add english birds

react/modules/module03/README.md
* To access the Unsplash API, first [join](https://unsplash.com/oauth/applications).
* Initially, your application will be in demo mode and will be rate-limited to 50 requests per hour. This is perfect for demo apps, trying out the API, and for educational purposes.
* The Unsplash API is made available as a free API. To use the API you must [abide by the terms](https://unsplash.com/api-terms) and [follow the API guidelines](https://help.unsplash.com/api-guidelines/unsplash-api-guidelines).
=> React task 3

stage0/modules/rs-school-intro/README.md
fix link to https://app.rs.school/profile
=> fix link to student profile

node/modules/websocket/README.md
NodeJS websocket task: Change control library from RobotJS to nut.js
=> fix: change nodejs websocket task

react/README.md, react/modules/module01/README.md, react/modules/module02/README.md, react/modules/module03/README.md, react/modules/module04/README.md, react/modules/module05/README.md, react/modules/module06/README.md
Made changes to the programme according to the new requirements
=> Updated first 6 modules

tasks/rsclone/rsclone.md
hey there o/
atm looks like so
will be as all previous
=> Add list bullets for 2022q1 works in RSClone

react/README.md, react/modules/module01/README.md, react/modules/module02/README.md, react/modules/module03/README.md, react/modules/module04/README.md, react/modules/module05/README.md, react/modules/module06/README.md
Updates the repo requirements for the react course to make them more clear for students
=> update repo requirements

react/modules/module01/README.md
=> feat: add typescript as a rule

react/modules/module02/README.md
=> feat: add hooks rule

stage1/modules/js-evolution/README.md
=> docs: replace url to deleted page about package-lock.json

tasks/rsclone/rsclone.md
hey there o/
add best RS Clones list
task: https://github.com/rolling-scopes-school/tasks/blob/master/tasks/rsclone/rsclone.md
=> Add best RS Clones 2022q3 stage#2

react/modules/graphiql.md
- Fixes this item, because it should redirect to the Main page, if I understand correctly
- Corrects some typos
- Adds the penalty Valera asked for
=> Update final task description

tasks/virtual-keyboard/virtual-keyboard-en.md
Fix grammar mistake in virtual-keyboard-en.md
=> fix: fix grammar mistake

stage2/modules/design-patterns/README.md
На `doka.guide` разделы переехали из `js` в `tools`
=> Design Patterns module - fix broken links

stage1/modules/webpack/README.md
Добавил новые вебинары по Webpack 5. Удалил старые, так как считаю их уже не актуальными.
=> Add materials to webpack module

stage0/modules/git/README.md
Purpose 🎯
Update documentation for git
Notes ✍️
- Added new video, wherein a simple manner it is told about the git and its use with the help of a GUI, because it's much easier to start from GUI instead with the command line. Since beginners do not have to start immediately with the console, its study can be moved to the advanced level;
=> docs: update links for stage 0 -> git

tasks/eCommerce-Application/Sprints/Sprint#3.md
added underline under CrossCheck criteria for better visual separation
added missing "- Total" to the third level headings to maintain uniformity in the display of total scores
=> docs: update Sprint#3.md

stage2/README.md
Замена битой ссылки на рабочую в строке:
> Задание "Презентация".
=> Fix presentation link in Week #11

stage1/modules/basic-tools/README.md
=> feat: update basic-tools module

tasks/library/library-part3.md
Library-part3.md add materials to study.
=> feat: library-part3.md add materials to study

stage1/modules/rs-school-intro/README.md
=> feat: translate module rs-school-intro

stage1/modules/git/README.md
* translate module to English
* partly updated sources of knowledge
=> feat: translate module git, update module sources

stage1/modules/js-fe-developer/README.md
=> feat: update Introduction to the profession of "JS/Front-end developer"

angular/modules/directives-and-pipes/README-ENG.md, angular/modules/directives-and-pipes/README-RU.md
Update module directives and pipes
=> Update module directives and pipes

tasks/angular/modules-services-routing.md
TICKET:
https://github.com/orgs/rolling-scopes-school/projects/5/views/1?pane=issue&itemId=38036803
DESCRIPTION:
Added a useful link for the to accomplish the lazy-loading module task
=> FIX: Angular- Coding task for Routing

react/modules/module03/README.md
Чтобы устранить все недопонимания)
https://discord.com/channels/794806036506607647/1015915849942573057/1163880864111939664
=> Update react module 3

tasks/cv/en/cv-github-hints.md, tasks/cv/en/cv-hints.md, tasks/cv/en/cv-stage0.md, tasks/cv/en/cv-stage1.md, tasks/cv/en/cv.md, tasks/cv/en/git-markdown.md, tasks/cv/en/git.md, tasks/cv/en/html-css-git.md
=> feat: add cv translations

react/modules/module01/README.md
Забыл вчера добавить эти строки для первого модуля
=> Update react module 1 penalties

stage1/modules/html-form/README.md
=> feat (JS/FE-2023Q4): Translate HTML Forms module

stage1/modules/functions/README.md
Update theory, add links with materials in English to every topic
Add additional educational materials
=> JavaScript. Scope and functions" Module update

react/modules/module02/README.md
Removes the item about running tests
=> Update react module 2

react/modules/module01/configs.md
https://github.com/rolling-scopes-school/tasks/pull/1254#issuecomment-1775093074
@SpaNb4
=> fix: remove eslint-plugin-prettier correctly

stage1/modules/git-recap/README.md
=> feat (JS/FE-2023Q4): Update and Translate Module "git-recap"

stage1/modules/js-basics/README.md, stage1/modules/js-basics/basic-operators.md, stage1/modules/js-basics/comments.md, stage1/modules/js-basics/data-types.md, stage1/modules/js-basics/functions.md, stage1/modules/js-basics/logical-operators.md, stage1/modules/js-basics/loops.md, stage1/modules/js-basics/type-conversion.md, stage1/modules/js-basics/variables.md
* Translate module to English
* Split module to a few separate submodules
* Update study materials
=> Translate, Split, Add Materials 'Основы JavaScript. Типы данных' Module 

react/modules/module02/README.md
Corrected the task's requirement for better readability.
=> react/modules/module02: fix task requirement in 5.4

tasks/angular/modules-services-routing.md
"It needs to be integrated within the AppModule. " written twice in a row. Removed 1 occurrence
=> Update modules-services-routing.md — remove the doubling of 1 sentence

stage1/modules/git/README.md
Reverts rolling-scopes-school/tasks#1287
=> Revert "fix: add language to Link text"

react/modules/module01/README.md, react/modules/module02/README.md, react/modules/module03/README.md, react/modules/module04/README.md, react/modules/module05/README.md, react/modules/module06/README.md
Updates the cross-check duration to avoid confusing students
https://discord.com/channels/794806036506607647/812644828164521984/1169543268342710272
=> [react] update cross-check duration

tasks/coffee-house/coffee-house.md
Allow Vite & Webpack in Coffee-House task
=> docs: explicitly allow bundlers in Coffee-House task

tasks/coffee-house/coffee-house-week1.md, tasks/coffee-house/coffee-house-week2.md, tasks/coffee-house/coffee-house-week3.md, tasks/coffee-house/coffee-house.md
=> docs: correct of comments

react/modules/module01/README.md, react/modules/module02/README.md, react/modules/module03/README.md, react/modules/module04/README.md, react/modules/module05/README.md, react/modules/module06/README.md
- Updates PR requirements to specify that PR need to be created into a previous task branch, not the master branch;
- Minor rephrasing.
=> [react] Update PR requirements

epam/README.md, tasks/materials/english.md
hey there o/
student found not working link https://www.english-polyglot.com/
removed it plus added some links recommended in discord
=> Remove not working link from english materials

stage1/modules/js-basics/loops.md
Wrong link, fixed with correct one.
=> docs: replace link of article

react/modules/module04/README.md
Removes mentions of view mode in module 4
Follow up PR https://github.com/rolling-scopes-school/checklist/pull/86
=> [react] module 4 remove view mode mentions

stage1/README.md
=> fix: links to parts of task "Coffee House" in program

stage1/modules/data-structures/README.md
Translated the Data Structures module and add English-language materials.
=> feat: [week-6] update and translate data structures task description

react/modules/module05/README.md
- Removed -20 points for usage of the state
=> Removed penalty for using state

Azure&MACH/modules/MACH_Introduction/readme.md
=> feat: add MACH Introduction

stage1/README.md
=> feat: update week#7

tasks/connections/milestone_1.registration.md, tasks/connections/milestone_2.login.md, tasks/connections/milestone_3.profile.md, tasks/connections/milestone_4.profile_update.md, tasks/connections/milestone_5.logout.md, tasks/connections/milestone_6.people_groups.md, tasks/connections/milestone_7.group_dialog.md, tasks/connections/milestone_8.conversation.md
=> edited mistake in tasks/connections/milestone_2.login.md

react/modules/module06/README.md
I fixed a few typos and grammatical errors and removed the repeated sentence and the sentence about tests because there are no tests in this task.
=> docs: react-module06, fix some typos in README.md

tasks/connections/milestone_2.login.md
typos after copypaste from signup task
=> fix typos milestone_2.login.md

tasks/connections/README.md, tasks/connections/milestone_1.registration.md, tasks/connections/milestone_2.login.md, tasks/connections/milestone_3.profile.md, tasks/connections/milestone_4.profile_update.md, tasks/connections/milestone_5.logout.md, tasks/connections/milestone_6.people_groups.md, tasks/connections/milestone_7.group_dialog.md, tasks/connections/milestone_8.conversation.md
Edited cross-check section. Removed items that relates to the need for code review by students.
=> edited general fines for tasks/connections project

tasks/connections/README.md, tasks/connections/milestone_3.profile.md, tasks/connections/milestone_4.profile_update.md, tasks/connections/milestone_7.group_dialog.md, tasks/connections/milestone_8.conversation.md
Added clarifying text to Angular Final project to make the description more clear
=> Edited Angular Connections project description text to make it clear

.github/ISSUE_TEMPLATE/proposal.md
=> feat: add issue template

tasks/coffee-house/coffee-house-week3.md
=> docs: fix comment for coffee-house-week3 task

stage1/README.md, stage1/modules/chrome-devtools/README.md
=> feat: update week-8

stage1/modules/node-materials/README.md, stage1/modules/node-materials/node/README.md
feat: add README for Node.js module
=> feat: add README for Node.js module

tasks/connections/README.md, tasks/connections/milestone_1.registration.md, tasks/connections/milestone_10.theme.md, tasks/connections/milestone_3.profile.md, tasks/connections/milestone_6.people_groups.md, tasks/connections/milestone_7.group_dialog.md, tasks/connections/milestone_8.conversation.md
- edited description for the page url;
=> Next update set to tasks/connections/README.md

stage1/README.md
=> feat: update week 9

tasks/connections/README.md, tasks/connections/milestone_6.people_groups.md, tasks/connections/milestone_7.group_dialog.md, tasks/connections/milestone_8.conversation.md
The next part of updates to tasks/connections project
=> edited tasks/connections project

stage1/modules/clean-code/materials/html-and-css-extended.md, stage1/modules/clean-code/materials/html-and-css.md
Fix errors in translation of 'indent' words. Translate forgotten 'BEM' word.
=> Translation fixes for clean-code module

stage2/modules/typescript-basic/README.md
Translation and Update of "TypeScript Basic" Module
I've decided to remove [this course](https://learn.microsoft.com/ru-ru/training/paths/build-javascript-applications-typescript/) from the `Theory` section, because its language of presentation seems pretty complex to understand, ultimately appearing more confusing than helpful in comprehending TS.  
I replaced it with [this course](https://scrimba.com/learn/typescript), which is entirely free, uses simpler words to convey information and, in my opinion, provides a better understanding for those who have never worked with TS before.
=> feat: [Week-2.1] Translation and Update of "TypeScript Basic" Module

stage1/modules/clean-code/clean-code-s1e1.md
=> [Week7] Clean Code S1E1 Fix Links

stage1/modules/clean-code/materials/commits.md, stage1/modules/clean-code/materials/generic-principles.md, stage1/modules/clean-code/materials/html-and-css-extended.md, stage1/modules/clean-code/materials/html-and-css.md
Fix Typos and Some Inaccuracies
Fix typos and some inaccuracies in the materials for the task
=> [Week7] Clean Code Fix Typos and Inaccuracies

stage1/README.md
=> feat: update weeks 10 & 11

stage1/README.md
Swap Modules "Chrome DevTools" and "Bundlers", Move "Client-Server Interaction Overview" to Week 11
- [ч] ❓ Other (specify: **\*\*\*\***\_\_\_\_**\*\*\*\***)
The course schedule requires an update to optimize the learning sequence. This includes swapping the "Chrome DevTools" and "Bundlers" modules, along with their related tests, and moving the "Client-Server Interaction Overview" module to Week 11 of stage#1. These changes aim to enhance the logical progression of the course material.
=> feat: Swap Modules "Chrome DevTools" and "Bundlers"

tasks/coffee-house/coffee-house-week3.md
> make task requirements and crosscheck criteria names consistent (implicit clarification of one of the crosscheck criteria)
> replace some crosscheck criteria names with task requirements names
=> feat: make task requirements and crosscheck criteria names consistent

stage2/modules/typescript-advanced/README.md
Translation and Update of "TypeScript Advanced" Module
Board task: [1429](https://github.com/orgs/rolling-scopes-school/projects/4/views/1?pane=issue&itemId=48497396)
=> feat: [Week-2.2] Translation and Update of "TypeScript Advanced" Module

stage2/modules/web-storage/README.md
Update and Translate "Web Storage" Module
Board task: [1435](https://github.com/orgs/rolling-scopes-school/projects/4/views/1?pane=issue&itemId=48573004)
=> feat: [Week-2.4] Update and Translate "Web Storage" Module

stage1/README.md, stage2/modules/technical-screening/README.md, tasks/interview-basic-coreJS.md
=> feat: update technical screening

stage2/README.md
=> feat: draft stage2 schedule

devops/modules/monitoring-configuration/README.md
The feature adds **"Monitoring with Prometheus and Grafana"** section (module 4) to DevOps course.
=> Add tasks for DevOps module 4

tasks/nonograms/README.md
Add new task for stage1 - Nonograms
https://github.com/rolling-scopes-school/tasks/issues/1351
=> feat: add final task Stage 1

tasks/nonograms/README.md
fix Nonograms task requirements 
=> Change Nonograms task requirements 

stage2/README.md
=> feat: update schedule week 2 stage#2

tasks/calculator.md, tasks/fancy-weather(en).md, tasks/fancy-weather.md, tasks/stage-0/fancy-weather.md
=> Added IP2Location.io API

stage2/modules/fp-basics/README.md
Update, Translate, and Structure Align "Functional Programming" Module
Issue: [1465](https://github.com/orgs/rolling-scopes-school/projects/4/views/1?pane=issue&itemId=50565219)
=> feat: [Week-2.5] Update, Translate, and Structure Align "Functional Programming" Module

stage1/README.md
=> feat: add roadmap

stage2/modules/single-page-application/README.md
=> feat: add SPA module

stage1/README.md, stage2/README.md
=> fix: update week 2.3

stage1/README.md, stage2/modules/technical-screening/README.md
=> feat: add technical screening issue link

stage2/modules/async/README.md
Update and Translate "Async Programming" Module
Issue: [1489](https://github.com/orgs/rolling-scopes-school/projects/4/views/1?pane=issue&itemId=52829574)
=> feat: [Week-2.7] Update and Translate "Async Programming" Module

tasks/migration-newip-to-ts.md
=> docs: add info about mocks endpoints to migration-newip-to-ts

stage2/README.md, tasks/interview-basic-coreJS.md, tasks/interview-corejs.md
=> feat: update CoreJS Interview #1

stage2/modules/code-review/README.md
Update the Link to the Practical Code Review Task
Replace TBD with [a link](https://github.com/rolling-scopes-school/tasks/tree/master/stage2/tasks/code-review) to the practical task Code Review
=> feat: update the link to the practical Code Review task

stage2/README.md
=> fix: update schedule

stage2/modules/single-page-application/README.md
Video links are mixed up in the module.
Video links are mixed up in the module.
Put the correct link according to the description.
=> fix: fix mixed up video links

stage2/tasks/puzzle/MentorsCheckCriteria.md
=> fix: update puzzle penalty

stage2/tasks/puzzle/README.md, stage2/tasks/puzzle/stories/RSS-PZ-04.md
=> feat: update criteria

stage2/modules/error-handling/README.md
Issue: [1523](https://github.com/rolling-scopes-school/tasks/issues/1523)
=> feat: [Week-2.9] Update and Translate "JavaScript Error Handling" Module

tasks/codewars/Codewars-2023Q4-FP.md
Большая часть задач на функциональное программирование и 3 задачи на реализацию встроенных функций.
=> Add codewars FP tasks for 2023q4 course

react/nextJsQuestions.md, react/questions.md
=> add: add new react questions and nextJsQuestions.md

react/questions.md, stage2/modules/error-handling/README.md, stage2/tasks/async-race/README.md, stage2/tasks/async-race/functional-requirements.md, stage2/tasks/async-race/non-functional-requirements.md
=> feat: update async-race

stage2/modules/restful-api/README.md
Translate and Update RESTful module
#1515
=> feat: translate REST module

stage2/tasks/async-race/README.md
=> fix: remove duplicate

react/modules/class-component/README.MD, react/modules/error-boundary/README.MD, react/modules/react-setup-env/README.md
[Issue](https://github.com/rolling-scopes-school/tasks/issues/1408)
По новой системе добавлены три темы стартового модуля:
- Setting Up React Environment
- Class Components in React
- Error Boundary in React 
Модули должны быть связаны с таском, потому ещё не готовы. Есть две ТОДО:
- Какие таски и тесты должны быть связаны с темами
=> feat: new module-system

stage2/tasks/rss-testing/README.md
creating a description for the RSS Testing task
This pull request is part of the "RSS-testing" task.
The specific criteria for evaluating this task will be added later.
=> feat: add rss-testing description

stage2/modules/async/README.md, stage2/modules/eventloop-animation/README.md
Translate and Update "Event Loop & Animation" Module
Issue: [1514](https://github.com/orgs/rolling-scopes-school/projects/4/views/1?pane=issue&itemId=54267194)
I remember we already brought up "Loupe" and "JavaScript Visualizer 9000" in the [Async Programming module](https://github.com/rolling-scopes-school/tasks/tree/master/stage2/modules/async), but I think they'd be just as fitting for this module too.
=> feat: [Week-2.7] Translate and Update "Event Loop & Animation" Module

react/modules/router/README.md
create react router module
#1446
=> feat: create react router module

stage2/README.md, stage2/modules/web-sockets/README.md
=> feat: create WebSockets module

stage2/tasks/fun-chat/README.md
Corrected scores in the fun-chat task in the delivery/reading messages criterion
=> docs: corrected points in fun-chat task

react/modules/react-evolution/readme.md
Please feel free to enhance this pull request with your contributions.
Task - [here](https://github.com/rolling-scopes-school/tasks/issues/1555)
=> feat: [React Course]: ~~Revolution~~ Evolution #1555

stage2/modules/testing/README.md
Issue [1464](https://github.com/rolling-scopes-school/tasks/issues/1464)
=> feat: translate module, add materials

stage2/README.md
=> feat: update schedule week-9

stage2/tasks/async-race/README.md
hey there o/
change in Async Race task description 'bag' 🛍 to 'bug' 🐞
=> stage#2 > Async Race > fix in description 'bag' 🛍 to 'bug' 🐞 typo

stage2/modules/testing/README.md
=> fix: typos in testing module

stage2/tasks/async-race/README.md
hey there o/
changed JS to TS to avoid potential misunderstandings among students
=> stage#2 > async race > change js to ts in requirements

stage2/README.md
=> feat: update schedule

react/modules/context-api/README.md, react/modules/context-api/readme.md
Please feel free to enhance this pull request with your contributions.
Task - [here](https://github.com/orgs/rolling-scopes-school/projects/7?pane=issue&itemId=49208490)
=> [React Course]: Module 3.2 Update: Expand and Update Context API

stage2/tasks/presentation/README.md, stage2/tasks/presentation/presentation-topics.md
=> feat: update presentation

node/modules/interview/README.MD
=> NodeJS interview topics

stage2/README.md
=> feat: update week 11

tasks/codewars/Codewars-2023Q4-DP.md
Добавила 2 дополнительные задачи
https://www.codewars.com/kata/simple-events
https://www.codewars.com/kata/advanced-events
=> Codewars design patterns tasks for 2023q4 course

stage2/modules/final-task/README.md
Translate and Revise "Preparation for Final Project" Module
=> feat: Translate and Revise "Preparation for Final Project" Module

react/modules/react-redux/README.md
Adds Redux module for the react course
=> [React Course]: Redux module

stage2/README.md, stage2/modules/ci-cd/README.md
=> feat: create module ci/cd

stage2/README.md
=> feat: update week 12

stage2/tasks/fun-chat/README.md
Fixing answers to questions from students in discord
=> docs: update q&a section

epam/async-race.md
=> Add notice for the deployment

stage2/tasks/fun-chat/README.md
hey there o/
@MikAleinik 
just noticed in discord chat the problem/question/bug/feature shown on the screenshot below - student checks the task in Opera browser, though seems usually it's mentioned in tasks (or maybe we should add it somewhere to the docs) to check tasks in Google Chrome, or it's considered by default... if it wasn't a plan to check your app working correctly in different browsers :)
also one more interesting question - if displaying error message in console is enough :?
just a suggestion for q&a session answers :)
=> stage#2 > fun-chat > add requirement to check in google chrome

stage2/modules/how-browsers-work/README.md
=> feat: update module Rendering Flow

stage2/README.md, stage2/modules/garbage-collection/README.md
=> feat: update week 14

tasks/interview-corejs.md
=> feat: update corejs2

stage2/README.md
=> feat: update stage2 schedule

react/README.md, react/modules/tasks/forms.md
Practical task for the Forms module in React
=> Added task for forms module in React

tasks/eCommerce-Application/Sprints/Sprint#2.md
Fix small misstype error in Sprint2 description, header section
There is a typo in the [Sprint 2 Overview description](https://github.com/rolling-scopes-school/tasks/blob/master/tasks/eCommerce-Application/Sprints/Sprint%232.md)  indicating the wrong number of issue:
`RSS-ECOMM-22`. Potentially could result in incorrect branch names
Fix this by setting the correct number of the issue `RSS-ECOMM-2_22`
=> fix: mistype error in Sprint2 description

stage2/tasks/fun-chat/README.md
Updating the description of the fanchat after the task is completed
- controversial criteria are clarified
- added item numbering to make it easier to find items during discussions
Issue #1622
=> Update FunChat description

angular/README.md, react/modules/tasks/class-components.md
=> feat: add eslint config requirement

angular/README.md, angular/modules/components/README-ENG.md, angular/modules/components/README-RU.md, angular/modules/directives-and-pipes/README-ENG.md, angular/modules/directives-and-pipes/README-RU.md, angular/modules/forms/README-ENG.md, angular/modules/forms/README-RU.md, angular/modules/http/README-ENG.md, angular/modules/http/README-RU.md, angular/modules/intro/README-ENG.md, angular/modules/intro/README-RU.md, angular/modules/modules-and-services/README-ENG.md, angular/modules/modules-and-services/README-RU.md, angular/modules/redux/README-ENG.md, angular/modules/redux/README-RU.md, angular/modules/routing/README-ENG.md, angular/modules/routing/README-RU.md, angular/modules/rxjs/README-ENG.md, angular/modules/rxjs/README-RU.md, angular/modules/unit-test/README-ENG.md, angular/modules/unit-test/README-RU.md
=> fix: fix angular modules, links

react/modules/graphiql.md
=> WIP: Started update of the final task

angular/modules/signals/README-ENG.md, angular/modules/signals/README-RU.md, tasks/angular/signals.md
=> feat: add signals task to angular.

tasks/angular/intro.md
=> fix: Angular - fixed Getting started in the intro task for Angular v18

tasks/angular/components-directives-pipes.md, tasks/angular/response.json
hey there o/
just found out that some of the videos' pics are not available/broken for imlementing fake search functionality, also getting errors in console (some of the courses seems moved to vk or other platforms)
new:
@Satlykov could you take a look at please
=> Angular - Update response.json

react/README.md, react/modules/tasks/forms.md
added tests in the course program and fixed name of the form task
=> fix: added tests in the course program and fixed name of the form task

react/modules/react-setup-env/README.md
=> Fixed husky link

react/modules/error-boundary/README.md
Removes the link to the duplicated content
=> React: remove duplicated link

tasks/angular/intro.md
hey there o/
according to students questions and proposals - let's add one line of info about creating private school repo and performing tasks in it to the first task only
=> Angular - Add info about creating private school repo (intro task)

react/modules/class-component/README.md
=> fix: remove duplicated link

react/README.md
Fix some mistakes.
Fix some mistakes in the README
Fixed some mistakes in the README
I just fixed the mistakes.
=> fix: Fix some mistakes in the README

react/modules/tasks/README.md
=> React - fix: update pr requirements

epam/async-race.md
Updating the requirements and evaluation of the epam/async race task
-- For React, the use of a state manager has been made mandatory
-- The description of the page content has been made more detailed
-- The points for completed items have been redistributed. Points related to the implementation of the race have been made significantly more expensive
-- Removed items, the implementation of which when using a "framework" is either very simple or automatic. (For example, implementing SPA or "All HTML content must be dynamically generated using JavaScript")
-- Change .md file)
=> docs: Update async race rules to make ponts more fair

epam/async-race.md, react/modules/tasks/routing.md
Temporarily removes the `unmount` requirement to prevent contradictions. In the future we may change the requirements according to https://discord.com/channels/794806036506607647/812644828164521984/1261223984087961610
=> React - update react routing task

react/modules/tasks/redux.md
=> Updated the task for the Redux to avoid confusion

react/README.md
=> Updated the schedule

tasks/angular/signals.md
hey there o/
one more line remained about testing implementation in Signals task :)
=> Angular - Remove one more line about tests implementation from fines in Signals

devops/modules/basic-configuration/README.md, devops/modules/ci-configuration/README.md, devops/modules/cluster-configuration/README.md, devops/modules/monitoring-configuration/README.md
Some spelling and wording fixes
Grammar fixes for the module
=> spelling fixes

tasks/train-a/admin/ride.md, tasks/train-a/admin/routes.md, tasks/train-a/order.md, tasks/train-a/sign-in.md, tasks/train-a/sign-up.md
Added detailed User Flow into Authorization pages.
Added details to the requirements.
=> added User Flow into Sign-In, Sign-Up pages

react/modules/tasks/final.md
=> Added templates for the final task

react/modules/tasks/final.md
=> Removed the adaptive layout requirement

tasks/train-a/admin/carriages.md, tasks/train-a/profile.md, tasks/train-a/readme.md, tasks/train-a/sign-in.md
=> Angular: Train-A. Edited links

react/modules/tasks/final.md
=> Removed inconsistency in requirements

tasks/train-a/admin/ride.md, tasks/train-a/admin/routes.md, tasks/train-a/admin/stations.md, tasks/train-a/readme.md, tasks/train-a/search-detail.md
Added specific error descriptions for http-request
Few 400 errors are added
=> Angular: A-Train. Added error description for http-requests

tasks/train-a/presentation.md, tasks/train-a/search-detail.md
=> Added presentation description for Angular: Train-A project

devops/modules/1_basic-configuration/task_1.md, devops/modules/1_basic-configuration/task_2.md, devops/modules/2_cluster-configuration/task_3.md, devops/modules/3_ci-configuration/task_4.md, devops/modules/3_ci-configuration/task_5.md, devops/modules/3_ci-configuration/task_6.md, devops/modules/4_monitoring-configuration/task_7.md, devops/modules/4_monitoring-configuration/task_8.md, devops/modules/4_monitoring-configuration/task_9.md, react/modules/tasks/final.md
=> Made corrections to the final task

react/modules/tasks/class-components.md
Setup React project with class components, error boundary, and API integration for search functionality
Set up a React project using Vite with TypeScript, integrated ESLint with strict TypeScript rules and eslint-plugin-react-compiler. Implemented class components for page structure, added error boundary, and set up API integration for search functionality.
Divided the page into two components: top section for Search input and button, and bottom section for displaying API search results. Utilized local storage to store and retrieve search terms. Implemented loading indicators (Spinner) for API requests and error boundary for error handling.
No screenshots or links needed for this change.
=> chore: Update task description for class components

devops/modules/1_basic-configuration/task_1.md, devops/modules/1_basic-configuration/task_2.md
=> The first task proposal for devops course

stage0/modules/js-functions/README.md
Fix: replace additional resource
The previous link is dead (with the github acc of its author)
Community provided a kind of fork of original material
=> Fix: replace additional resource

devops/modules/1_basic-configuration/task_1.md
- **Brief Overview:** since devops folder is not added to ci, unformatted files from this folder cause problems when making changes to other parts of the project (error in checks during PR creation).
- **Implementation Approach:** manually ran the `format` script
=> refactor: format devops task_1.md

.github/CODEOWNERS, README.md
=> refactor: update codeowners

devops/modules/1_basic-configuration/task_2.md
=> Proposal for the second task of DevOps course

stage1/modules/self-introduction/README.md
Update self-intro examples with the latest ones
=> feat: update self-intro examples

stage1/modules/js-basics/data-types.md
Remove codewars link from https://github.com/rolling-scopes-school/tasks/blob/master/stage1/modules/js-basics/data-types.md
=> Remove codewars link

stage2/README.md
- the Async Race task moved by 1 week
- modules required to the Async Race task are shifted
- week 19 clarified and divided
=> [2024Q4] Update Stage#2 schedule

devops/modules/3_ci-configuration/task_5.md
In order to provide more clarity for Task 5, application name was specified
- [ x ] ⚙️ Update to an existing task
- [ x ] 🐛 Fix in a task or related content
Added app definition for students
- [ x ] ✅ I have performed a self-review of my own code.
- [ x ] 🚫 My changes generate no new warnings or errors.
=> Provided Application name for Task 5

tasks/christmas-shop/christmas-shop-part3.md
=> [2024Q4] Update Christmas Shop part 3

stage1/modules/clean-code/README.md, stage1/modules/clean-code/clean-code-s1e1.md, stage1/modules/clean-code/materials/commits.md, stage1/modules/clean-code/materials/generic-principles.md, stage1/modules/clean-code/materials/html-and-css-extended.md, stage1/modules/clean-code/materials/html-and-css.md
=> [2024Q4] feat: update clean code

stage1/modules/data-structures-and-algorithms/data-structures.md
- **Brief Overview:** add links to data-structures.md summary for better navigation
=> docs: add nav links to data-structures.md summary

react/README.md, react/modules/context-api/README.md, react/modules/forms/README.md, react/modules/performance/README.md, react/modules/tasks/performance.md
Updated the perfromance task to contain the details about the React dev tools usage
=> Updated performance task. Added referencies to the new React api

react/modules/tasks/final.md
=> Updated final task

react/modules/tasks/routing.md
changed points and penalties for the tests requirement
=> update the React routing and tests task

stage2/tasks/puzzle/stories/RSS-PZ-11.md, stage2/tasks/puzzle/stories/RSS-PZ-13.md
Fix broken links to [RSS-PZ-28.md](https://github.com/rolling-scopes-school/tasks/blob/master/stage2/tasks/puzzle/stories/RSS-PZ-28.md) in [RSS-PZ-11.md](https://github.com/rolling-scopes-school/tasks/blob/master/stage2/tasks/puzzle/stories/RSS-PZ-11.md) and [RSS-PZ-13.md](https://github.com/rolling-scopes-school/tasks/blob/master/stage2/tasks/puzzle/stories/RSS-PZ-13.md)
=> [Stage 2, puzzle]: fix broken links to RSS-PZ-28.md

react/modules/tasks/class-components.md
In accordance with the discussion in discord and information from the introductory webinar on the React course, I added permission to use CSS frameworks to the task.
=> Add CSS frameworks permission to react class-components task

stage2/tasks/TypeScriptEssentials/README.md, stage2/tasks/TypeScriptEssentials/stories/RSS-TSE-09.md, stage2/tasks/TypeScriptEssentials/stories/RSS-TSE-10.md
The requirements for the repository have been changed from a school private repository to a personal private repository. In connection with this change, sections `Branch Management`, `Pull Requests` and `Task Submission to Cross-Check Rules` have been supplemented and updated
=> [Stage 2, typescript essentials]: change repository requirements for a task

react/modules/tasks/project-setup.md
feat: Attention:
The final setup might differ based on course requirements or individual preferences. 
⚠️⚠️⚠️ Additionally, the project setup does not involve class components, and the configuration file should be moved to the setup section for clarity.
=> feat: Attention

stage1/modules/oop-basics/README.md
Add a useful link to a video that precisely describes what UML is  https://www.youtube.com/watch?v=6XrL5jXmTwM
Added a useful link to a video that precisely explains what UML is, to help better understand its concepts
=> [Stage 1] Update OOP Module

stage2/README.md
=> [Stage#2] Update README.md

tasks/migration-newip-to-ts.md
Change links for course logo and course link
=> News API task links

stage2/tasks/decision-making-tool/README.md
- **Brief Overview:** the github readme does not match the npmjs readme. the npmjs readme is more consistent, so change the links to npmjs. additionally updated the links to more relevant feedback forms.
=> docs: update package and form links

react/README.md, react/modules/tasks/nextjs-ssr-ssg.md
=> Updated schedule

stage2/tasks/decision-making-tool/README.md
update allowed libraries. replace react-oriented css-in-js lib to framework agnostic libs. update some linter rules
=> [Stage 2, Decision Making Tool]: update allowed libraries

react/modules/tasks/nextjs-ssr-ssg.md
Fix the link leading to PR Example
=> fix: fix PR Example RSS docs link

react/interview.md
Update the React interview requirements
=> Update the React interview requirements

stage2/tasks/async-race/README.md
Non-functional requirements section updated to match [non-functional-requirements.md](https://github.com/rolling-scopes-school/tasks/blob/master/stage2/tasks/async-race/non-functional-requirements.md) file
=> [STAGE 2, async-race]: update non-functional requirements in README.md

react/modules/tasks/nextjs-ssr-ssg.md
=> Next.js app router focused task

tasks/museum/museum-stage1.md
=> Update museum-stage1.md - fix the broken link

react/README.md, react/modules/portals/README.md, react/modules/tasks/final.md
=> Updated the schedule. Added portals theory

react/modules/tasks/nextjs-ssr-ssg.md
=> Next.js: add next intl

react/modules/tasks/tests.md
=> [React] fix: unit testing description

react/questions.md
=> feat: add new react interview questions

stage0/modules/js-functions/README.md
Update links to `reverse-int` and `human-readable-number` tasks repositories
=> [STAGE-0]: update links to 'reverse-int' and 'human-readable-number' tasks repositories

react/modules/tasks/final.md
=> Updated the final task with 2 more options

react/modules/tasks/nextjs-ssr-ssg.md
=> feat: ## FAQ (Frequently Asked Questions)

react/modules/tasks/functional-routing.md
=> [React]: wrap <Outlet> in backticks

stage0/README.md
update link to core-js-101(S0) task repo in README
=> [STAGE-0]: update link to core-js-101-stage0 task

stage0/modules/data-structures-part-1/README.md
Changed tasks's links to correct ones for  towel-sort and morse-decoder
=> [STAGE-0]: update links to 'towel-sort' and 'morse-decoder' tasks repositories

react/modules/tasks/performance.md
=> Updated points

angular/modules/rsclone/README.md, react/modules/tasks/performance.md
=> Added penalties for the missing report, ran the format command

stage1/README.md
- update dates for the first two weeks
- remove roadmap link
=> [Stage1] update first two weeks dates, remove roadmap from README

react/modules/tasks/final.md
=> Changed how points are added
