tasks/git-markdown.md

Fix typos in "Markdown & Git" task description

---

tasks/codejam-pallete.md

change "material ui" to "material design" due to conflicting requirements: "you cannot use react", but at the same time material ui is the react ui framework.

Codejam Pallette: change item in task limitations

---

tasks/codejam-culture-portal.md

On this moment we cant meet Author's name and authors years of life in "Page of an author" requires. I suggest to add it.

docs: add authors required information

---

tasks/presentation.md

There's a considerable number of students who reserve slots for live presentation, but fail to appear and notify in advance, thereby forfeiting chances of those students who were too late to reserve slots. Also, many students don't provide any contact details, thus making it impossible for the jury to reach them.

Proposals for reservation procedure

---

stage1/modules/js-evolution/README.md

Url for "Updating a package" and for "Removing a package" is the same

fix: fix url for "Removing a package" npm list item

---

stage1/modules/data-structures/README.md

Изменение: поменять местами пункты выполнения задач `basic-js` и `basic-js-ds` и добавить к первому подпункт, подчёркивающий тот факт, что от судентов не ожидается выполнение всех задач.
Когда я проходил модуль, то заметил за собой и другими студентами, что многие занимались именно `basic-js` и не прикоснулись к `basic-js-ds` из-за большого количества задач (многие из которых сложные) в первом. Из-за порядка пунктов можно подумать, что `basic-js` должен выполняться первым, но `basic-js-ds` намного легче и короче, и за оба набора задач даётся одинаковое количество баллов.
Так как многие не успевают выполнить первый набор задач, из-за чего не прикосаются ко второму, и чтобы подчеркнуть дух необязательности выполнения большого количества задач первого набора, я предлагаю поменять их местами …

Tweak README of stage1/modules/data-structures

---

tasks/migration-newip-to-ts.md

Using ESLint 'no-explicit-any' rule is a technical requirement in this task, but it's not checking in cross-check requirements. So I decided to add it to cross-check requirements and penalties.
Please have a look and consider merging PR.

Feat(migration-to-ts): add ESLint 'no-explicit-any' rule to cross-check requirements

---

node/modules/nodejs-installation/README.md

The link [https://nodejs.dev/learn/how-to-install-nodejs](https://nodejs.dev/learn/how-to-install-nodejs) is no longer available.
Replaced by the correct one: [https://nodejs.dev/**_en_**/learn/how-to-install-nodejs](https://nodejs.dev/en/learn/how-to-install-nodejs)

fix: update how to install node.js link

---

tasks/rsclone/rsclone.md

hey there o/
just noticed - forgot closing 'details' tag after games list for 2022q3 examples and all the previous went into the same drop down list
now:
will be as should:
ty <3
task: https://github.com/rolling-scopes-school/tasks/blob/master/tasks/rsclone/rsclone.md

Add closing details tag after RSClones list

---

tasks/async-race.md

hey there o/
changed link to https://docs.rs.school/#/en/pull-request-review-process
that insists to complete stage#2 tasks in school's private repos, unless otherwise specified in a task
plus reminder to submit pr for mentor's check and deploy for cross-check

stage#2 - Async Race - Change link to repo requirements

---

stage2/modules/testing/README.md

https://github.com/rolling-scopes-school/tasks/tree/master/stage2/modules/testing
Change links to the documentation. The previous version leads to not-found page

docs: change documentation link

---

react/modules/module01/README.md

Short description: since the writing of tests will begin only in module 3, there is no need for this point of the [Cross-code-review process](https://github.com/rolling-scopes-school/tasks/tree/master/react/modules/module01#cross-code-review-process): 
- Run tests using special command in package.json file, all tests should pass, test coverage should be shown after running all the tests.
This item can be replaced with it:
- Run prettier using special command in package.json file, make sure that fix commands fixes issues

docs: react module#1 - replace the item about run test with run prettier

---

react/modules/module01/README.md

Short description: since the writing of tests will begin only in module 3, there is no need for this point of the [Cross-code-review process](https://github.com/rolling-scopes-school/tasks/tree/master/react/modules/module02#cross-code-review-process): 
- Run tests using special command in package.json file, all tests should pass, test coverage should be shown after running all the tests.
This item can be replaced with it:
- Run prettier using special command in package.json file, make sure that fix commands fixes issues

docs: react module#2 - replace the item about run test with run prettier

---

react/modules/module01/README.md
react/modules/module01/configs.md

added minor clarifications
delete eslint-plugin-prettier from Recommended libraries
update prettier printWidth (according to official recommendations )
According to official documentation: 
```
These plugins were especially useful when Prettier was new.
But these days you can run prettier --check . 
and most editors have Prettier support" и "They are slower than running Prettier directly
```

docs: update react-components readme

---

tasks/angular/intro.md

hey there o/
noticed angular site with .ios instead of .io
plus made links to start with new line

Angular Intro .md: fix typo in angular site name

---

react/modules/module01/configs.md

удалил plugin:prettier/recommended из extends (из-за которого на текущий момент ошибка)
убрал флаг noImplicitAny в тс конфиге, так как strict: true автоматически активирует noImplicitAny

docs: update react-components config

---

tasks/angular/intro.md

Mandatory flag noImplicitAny is not nessasary because "strict: true" automatically enables noImplicitAny

docs: update evaluation criteria in ng intro

---

stage1/modules/functions/README.md

The [previous link](https://www.geeksforgeeks.org/concept-of-javascript-closures-inside-loops/) to Closures and Loops has been corrected due to errors in it.
This is an example from that link and it will cause difficulties for students:
But the result of the code execution will be:
The mistake is related with **var** and **let**.
Students will face the same two questions in the test with var and let.
I suppose that the [new link](https://www.freecodecamp.org/news/thrown-for-a-loop-understanding-for-loops-and-timeouts-in-javascript-558d8255d8a4) added in PR is more correct. For example, here are the correct explanation for the same function: 
-----------------
And correct explanation for the function with var:

fix: module functions stage1

---

stage1/README.md

Renamed the module link in the Stage1 Readme file from "Adaptive layout markup" to "Responsive Web Design" to match the module title.

fix: rename stage1 module link

---

react/modules/graphiql.md

Instead of hard-coded API provide option for user to change the GraphQL endpoint.
Support of Unicode passwords.
Add code smell penalty from previous tasks.

[react] Final task - improve language & grammar. User-specified endpoint

---

tasks/coffee-house/coffee-house-week1.md

- This pull request addresses a misunderstanding regarding the use of the `:active` pseudo-class in the task. Since the task creators did not plan for the use of the :active pseudo-class, the requirement for a mandatory smooth state transition on click has been removed to align with the original task intent.
- Modified the task conditions to eliminate the requirement for a mandatory smooth state transition on click.
- Ensured clarity by removing potential confusion caused by the unintended inclusion of the :active pseudo-class.

docs: fix interactivity, exclude :active in coffee-house-week1.md

---

tasks/angular/NgRX.md

Edited few mistakes in requirements for Youtube app.

corrected description for angular/ngrx practical task

---

react/modules/graphiql.md
react/modules/module01/README.md
react/modules/module02/README.md
react/modules/module03/README.md
react/modules/module04/README.md
react/modules/module05/README.md

hey there o/
not for the first time notice PR looking e.g. like this
one more
which makes cross-check process way more difficult and taking more time
let's subtract 10 points to push students to follow mentioned in docs requirements

React: Add penalties for not following PR requirements

---

stage1/modules/client-server/README.md

Translation and Update of Client-Server Interaction Module
- [Board task](https://github.com/rolling-scopes-school/tasks/issues/1347)

feat: [Week-10] Translation and Update of Client-Server Interaction Module

---

react/modules/forms/README.md

Add Forms module for the React course

feat: [React Course]: Module React Forms

---

epam/async-race.md
tasks/eCommerce-Application/Readme.md
tasks/eCommerce-Application/Sprints/Sprint#1.md
tasks/eCommerce-Application/Sprints/Sprint1/RSS-ECOMM-1_13.md
tasks/eCommerce-Application/Sprints/Sprint1/RSS-ECOMM-1_16.md
tasks/eCommerce-Application/Sprints/Sprint1/RSS-ECOMM-1_19.md

Update `eCommerce` task description to allow alternative testing framework `Vitest` in addition to `Jest`

docs: allow Vitest as alternative testing framework for eCommerce task

---

react/modules/nextjs-ssr-ssg/README.md
react/modules/tasks/nextjs-ssr-ssg.md

Nextjs module

---

stage0/modules/git/README.md

The old link to SSH key generation was broken. I have updated the link to the official guidelines from GitHub.

docs(git): change link to hot generate SSH key

---

tasks/angular/components-directives-pipes.md

hey there o/
changed 'there should be one' to 'at least one' standalone component, as students afraid to create more, though angular 18 by default generates standalone components and they are way more convenient
plus updated links for content projection and standalone components so that they lead to the new docs https://angular.dev/

Angular - Update standalone requirements task 2 youtube-app

---

angular/README.md

1. I changed `Juli` to the correct name for the month, `July`
2. Formated date style to similar like in other folders [date, year]
Related Issues:

docs(angular): change month name to correct

---

tasks/train-a/admin/readme.md
tasks/train-a/readme.md
tasks/train-a/sign-in.md
tasks/train-a/sign-up.md

hey there o/
changed maximum number in teams to 4

Angular - train-a - change maximum number in teams

---

angular/modules/components/README-ENG.md
angular/modules/directives-and-pipes/README-ENG.md
angular/modules/forms/README-ENG.md
angular/modules/http/README-ENG.md
angular/modules/modules-and-services/README-ENG.md
angular/modules/redux/README-ENG.md
angular/modules/routing/README-ENG.md
angular/modules/rxjs/README-ENG.md
angular/modules/signals/README-ENG.md
angular/modules/unit-test/README-ENG.md
tasks/angular/components-directives-pipes.md
tasks/angular/forms.md
tasks/angular/intro.md
tasks/angular/modules-services-routing.md
tasks/angular/rxjs-observables-http.md

hey there o/
- noticed outdated links and updated them in tasks and modules to lead to the new angular.dev site
- plus added note in second task that design and colour scheme of the app maybe one in one as offered or by a student's taste
plus agree with this statement
https://angular.dev/guide/components/importing
- so added in components task notice that in future tasks students will be asked to create some ngmodules if they have never dealt with to know how to work with legacy code
- and reformulated in modules services routing task requirement of transforming the whole app into fully ngmodules approach to requirement that some of the components can be ngmodules based on mentors final desicion
- added youtube link about shared modules can be considered as antipattern
- also we had …

Angular - links updates in tasks/modules plus note about design and standalone/modules architecture

---

devops/modules/3_ci-configuration/task_4.md

in order to simplify the task - HTTPS implementation is removed from task4
- [ x ] ⚙️ Update to an existing task
- [ x ] 🐛 Fix in a task or related content
Points have been rearranged a bit. HTTPS implementation have been removed from the task. 
- [x ] ✅ I have performed a self-review of my own code.
- [x ] 🚫 My changes generate no new warnings or errors.

Remove HTTPS from task_4

---

tasks/christmas-shop/christmas-shop-part1.md

In the [Christmas Shop task. Part-1](https://github.com/rolling-scopes-school/tasks/blob/master/tasks/christmas-shop/christmas-shop-part1.md#crosscheck-criteria-110-points) points for the interactivity section were 38 points, instead of 36. Because of this, the total number of points for the task was 112, instead of 110

[stage-1] reduce interactivity points from 4 to 2 (christmas-shop-part-1 task)

---

stage1/modules/sass/README.md

Delete unworking link to https://sherocommerce.com/what-is-a-css-preprocessors-why-use-them/
Broken link in description
I suggest delete broken link. Link in the task transfers us to the main page site  (https://sherocommerce.com/) which doesn't consist necessary information about SASS. 
- [ +] ✅ I have performed a self-review of my own code.
- [ +] 📝 I have commented my code, particularly in hard-to-understand areas.
- [ +] 🔧 I have made corresponding changes to the documentation (if applicable).
- [ +] 🚫 My changes generate no new warnings or errors.

Update README.md (Broken link in description)

---

tasks/christmas-shop/christmas-shop-part3.md

[2024Q4] Update christmas-shop task

---

devops/modules/4_monitoring-configuration/task_7.md

This change is intended to refactor Task 7 for AWS and DevOps course to provide more information and details for the task completion.

refactor: DevOps and AWS course task 7

---

devops/modules/4_monitoring-configuration/task_8.md

refactor: DevOps and AWS course task 8

---

react/modules/forms/README.md
react/modules/performance/README.md
react/modules/tasks/class-components.md
react/modules/tasks/forms.md
react/modules/tasks/performance.md
react/modules/tasks/project-setup.md
react/modules/tasks/redux.md
react/modules/tasks/routing.md

Created a new module "Performance" (Theory is still pending). Added task for the module.
Updated existing modules - put application requirements first.
Extracted project setup details to a separate file and linked it in 3 tasks.

Added a new module for the performance. Updated previous modules

---

react/modules/error-boundary/README.md

Broken link fix for React Error Boundaries theory module, providing alternative source.
Original link to codepen is broken - it returns error 404. New link works.
Since original link is broken, I'm not 100% sure what was there. But based on original URL I managed to find other sources that mention this URL and most likely show original content (see such links below). Based on those sources, offered change provides equivalent alternative to broken link.
- Original broken link: https://codepen.io/gaearon/pen/wqvxGa?editors=0010
- Broken link mentioned together with what's most likely a content of lost link: https://ru.stackoverflow.com/questions/1060595/react-error-boundaries-предохранители-Странное-поведение
- …

fix: change broken link to alternative

---

react/modules/tasks/nextjs-ssr-ssg.md

Fixes the coverage percentage for penalties to match the application requirements

fix: react-nextjs coverage

---

react/modules/tasks/forms.md
react/modules/tasks/performance.md

Fixed docs links till the end of the current React course. 

fix: fix docs links till the end of the React course

---

stage2/tasks/async-race/non-functional-requirements.md

Update requirements due to Airbnb style guide incompatibility, clarify allowed CSS libraries, and restrict type assertions.
1.  Replace Airbnb style guide with Unicorn style guide;
2.  Define allowed CSS libraries;
3.  Restrict type assertions and non-nullable type assertions;

docs: clarify and update requirements of the async-race task
